### ISSUE TITLE
How to add new backends/compilers?

### ISSUE THREAD

**Issue by raphaelDkhn** [jafioti/luminal#41]
Hi, great project! I'd like to add a new backend/compiler. Is there a step-by-step guide for this to make sure I don't forget anything?

**Comment by jafioti** [comment]
There isn't yet a good guide but I'd look at crates/luminal_cuda or crates/luminal_metal for a good example of how to add a new backend. Metal is more fleshed out but also a bit more complex, cuda is slower but simpler currently.
