### ISSUE TITLE
Optimize clone

### ISSUE THREAD

**Issue by npuichigo** [jafioti/luminal#59]
I'm wondering why there're many clones although we already have moved `self` and other parameters.

https://github.com/jafioti/luminal/blob/a5d292a47d4e5b6f8677a97fd0c81a1cd9233e03/src/shape/symbolic.rs#L258-L261

Please help me to check if I'm right?

**Comment by jafioti** [comment]
You are right there can be far less. It has to do with the ExpressionStorage trait, which only implements IntoIterator which consumes the object. Instead we should implement IntoIterator on &S so that it yields &Term such that cloning isn't needed

**Comment by npuichigo** [comment]
Yes. But since we are already consuming the object here, maybe just removing the `clone` and let `into_iter` consume `self` is enough?

**Comment by jafioti** [comment]
I think it is used more than once there

**Comment by npuichigo** [comment]
At least removing `clone` in L258 compiles and passes the unit test.

**Comment by jafioti** [comment]
I removed most of the clones by adding an .iter_ref() function to expressionstorage, which creates a borrowed iterator.

**Comment by jafioti** [comment]
I'll go ahead and close this, there's not many clones left in symbolic.
