### ISSUE TITLE
Allow noop `expand`s

### ISSUE THREAD

**Issue by swfsql** [jafioti/luminal#64]
Hi, is it possible to allow noop expands?

Example:
```rust
#[test]
fn noop_expand() {
    let cx = Graph::new();
    let a = cx.tensor::<R1<1>>();
    let mut b = a.clone();
    b = a.expand::<R1<1>, Axis<0>>();
}
```
Note: the example compiles successfully for `R0`, as the noop reduce/broadcast is allowed for this case.

This results in the following compilation error:
```
error[E0277]: the trait bound `(luminal::shape::Const<1>,): luminal::shape::BroadcastShapeTo<(luminal::shape::Const<1>,), _>` is not satisfied
   --> src/main.rs:7:15
    |
102 |         b = a.expand();
    |               ^^^^^^ the trait `ReduceShapeTo<(luminal::shape::Const<1>,), _>` is not implemented for `(luminal::shape::Const<1>,)`, which is required by `(luminal::shape::Const<1>,): luminal::shape::BroadcastShapeTo<_, _>`
    |
    = help: the following other types implement trait `ReduceShapeTo<S, Ax>`:
              <() as ReduceShapeTo<(), Axis<0>>>
              <(A, B) as ReduceShapeTo<(), Axes2<0, 1>>>
              <(A, B) as ReduceShapeTo<(A,), Axis<1>>>
              <(A, B) as ReduceShapeTo<(B,), Axis<0>>>
              <(A, B, C) as ReduceShapeTo<(), Axes3<0, 1, 2>>>
              <(A, B, C) as ReduceShapeTo<(A, B), Axis<2>>>
              <(A, B, C) as ReduceShapeTo<(A, C), Axis<1>>>
              <(A, B, C) as ReduceShapeTo<(A,), Axes2<1, 2>>>
            and 113 others
    = note: required for `(luminal::shape::Const<1>,)` to implement `luminal::shape::BroadcastShapeTo<(luminal::shape::Const<1>,), _>`
note: required by a bound in `movement::<impl luminal::graph_tensor::GraphTensor<S>>::expand`
   --> luminal/src/hl_ops/movement.rs:17:12
    |
15  |     pub fn expand<Dst: Shape, Ax: Axes>(mut self) -> GraphTensor<Dst>
    |            ------ required by a bound in this associated function
16  |     where
17  |         S: BroadcastShapeTo<Dst, Ax>,
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^ required by this bound in `movement::<impl GraphTensor<S>>::expand`
```

Note: I don't know which `Axis` would be valid for for a shape that "expands/reduces" to itself (currently `Axis<0>` is allowed for `R0`). Maybe any type could be allowed?

One possibility would be generalizing the noop defined for `R0`, into:

```rust
impl<S: Shape + HasAxes<AnyAxis>, AnyAxis> ReduceShapeTo<S, AnyAxis> for S {}
```

Thanks in advance!

**Comment by swfsql** [comment]
I had a problem with noop expands + autograd ([link to example](https://github.com/swfsql/luminal/blob/linear_bias_test/examples/bias_test/src/main.rs#L50)).

The error was on [autograd.rs:197](https://github.com/jafioti/luminal/blob/f61d53f859293d4c5e4d57d264dfc423a98007e0/crates/luminal_training/src/autograd.rs#L197):
```
thread 'main' panicked at crates/luminal_training/src/autograd.rs:197:63:
index out of bounds: the len is 1 but the index is 1
...
   6: luminal_training::autograd::add_grad
             at ./crates/luminal_training/src/autograd.rs:197:63
   7: <luminal_training::autograd::Autograd as luminal::compiler_utils::Compiler>::compile
             at ./crates/luminal_training/src/autograd.rs:107:21
   8: luminal::graph::Graph::compile
             at ./src/graph.rs:137:22
   9: bias_test::main
             at ./examples/bias_test/src/main.rs:50:18
```

---

On another note, having noop expands disallows some inferences of the expands by just specifying the axis, that is for the cases where there would be the noop and non-noop possibilities.

**Comment by jafioti** [comment]
@swfsql Can you instead try with a hidden size of R1<5> or something? I wonder if there's a mixup between R0 (scalar) and R1<1> (also a scalar).Besides that I'm not too sure how this would cause an issue. noop expands are pretty much just a compile-time thing that doesnt get reflected at all in the runtime shapetrackers since the shape isnt actually expanding, so I don't see how the autograd would know the noop is even happening

**Comment by swfsql** [comment]
@jafioti The `R1<1>` shape in the example is the input, and by changing it to `R1<5>`, adapting other stuff such as `impl Module<GraphTensor<R1<5>>> for /*..*/`, the same error message still happens, and on the same line.

**Comment by swfsql** [comment]
To add more info, this example is a minimal one that reproduces some error, but I had another similar error (not from a minimal example) where the error wasn't on the _permute undoing_ operation (in autograd), but on the _expands undoing_ operation.

But since the minimal example pointed to the permute undoing, perhaps both would be fixed/avoided if the minimal example passes.

**Comment by jafioti** [comment]
Agreed. I'll take a look at your branch

**Comment by swfsql** [comment]
Thanks! And sorry for not pointing exposing the changes more clearly. I'll open and close a pr so the changes can be seen online also.

**Comment by jafioti** [comment]
I believe this is now solved with runtime shapes. Feel free to reopen if it isn't!
