### ISSUE TITLE
Cuda `GatherCompiler` fails on low dimensionality

### ISSUE THREAD

**Issue by swfsql** [jafioti/luminal#70]
Hi, I've encountered a failure on Cuda's `GatherCompiler` compilation pass.

I've extracted the one_hot functionality from embeddings and applied it to a transformation of some input tensor. It succeeds if the input is a `R1`, but fails if it's a `R0`.

I've added a PR containing an example of a failing test.

**Comment by jafioti** [comment]
Solved with #71
