### ISSUE TITLE
cargo build --release --features cuda,   error!

### ISSUE THREAD

**Issue by ricesin888** [jafioti/luminal#74]
error[E0283]: type annotations needed
   --> crates\luminal_cuda\src\elementwise_fusion.rs:116:86
    |
116 |                     .unwrap_or_else(|| vec![(expression_b.clone(), ShapeTracker::new(&[]))]);
    |                                                                    ----------------- ^^^ cannot infer type for type parameter `impl Into<Expression> + Copy` declared on the associated function `new`
    |                                                                    |
    |                                                                    required by a bound introduced by this call
    |
    = note: cannot satisfy `_: Into<GenericExpression<ArrayVec<[luminal::shape::Term; 20]>>>`
note: required by a bound in `luminal::shape::ShapeTracker::new`
   --> E:\rust\luminal\src\shape\tracker.rs:18:29
    |
18  |     pub fn new(dims: &[impl Into<Expression> + Copy]) -> Self {
    |                             ^^^^^^^^^^^^^^^^ required by this bound in `ShapeTracker::new`

error[E0283]: type annotations needed
   --> crates\luminal_cuda\src\prim.rs:706:60
    |
706 |                 .input(function_node, 0, ShapeTracker::new(&[]))
    |                                          ----------------- ^^^ cannot infer type for type parameter `impl Into<Expression> + Copy` declared on the associated function `new`
    |                                          |
    |                                          required by a bound introduced by this call
    |
    = note: cannot satisfy `_: Into<GenericExpression<ArrayVec<[luminal::shape::Term; 20]>>>`
note: required by a bound in `luminal::shape::ShapeTracker::new`
   --> E:\rust\luminal\src\shape\tracker.rs:18:29
    |
18  |     pub fn new(dims: &[impl Into<Expression> + Copy]) -> Self {
    |                             ^^^^^^^^^^^^^^^^ required by this bound in `ShapeTracker::new`

**Comment by jafioti** [comment]
yeah a ton of changes for runtime shapes were recently pushed but haven't been brought over to cuda yet. I will be working on that this week.

**Comment by jafioti** [comment]
I believe this will work now. Feel free to reopen if it doesn't
