### ISSUE TITLE
[Bug] : Tests won't compile due to dfdx error

### ISSUE THREAD

**Issue by raphaelDkhn** [jafioti/luminal#77]
I encountered compilation errors when running tests of Luminal. The issue arises a bunch of compilation errors related to `dfdx` crate. 

**Steps to Reproduce:**
```shell
cargo run test
```

**Expected Behavior:** 
The tests should compile and run without any issues.

**Actual Behavior:** 
The compilation fails with a bunch of errors, like the following:

```shell
error[E0310]: the parameter type `T` may not live long enough
  --> /Users/raphaeldoukhan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/dfdx-0.13.0/src/nn/flatten.rs:27:9
   |
27 |         input.try_reshape()
   |         ^^^^^^^^^^^^^^^^^^^
   |         |
   |         the parameter type `T` must be valid for the static lifetime...
   |         ...so that the type `T` will meet its required lifetime bounds
   |
help: consider adding an explicit lifetime bound
   |
18 | impl<const C: usize, const H: usize, const W: usize, D: Device<E>, E: Dtype, T: Tape<E, D> + 'static>
   |                                                                                            +++++++++
```

**Luminal Version:**
Latest commit: [d311003](https://github.com/jafioti/luminal/commit/d311003e8eec47a121ab13b326fc322da57e2b89)

**Comment by jafioti** [comment]
I'm not sure what cargo run test is doing there, just use `cargo test`. I just pulled main, cleaned, rm Cargo.lock, and ran `cargo test` and didn't see any issues.

**Comment by raphaelDkhn** [comment]
Sorry, I made a typo when writing the issue. I actually ran `cargo test`. Hmm weird, probably an error on my system, I'll investigate. Thanks!

**Comment by raphaelDkhn** [comment]
It was due to my `rustc` version. I was using a nightly version. With the last stable version it's working.
